# Trigger by `git push origin tag v*`
on:
  push:
    tags:
      - 'v*'

name: Deploy

jobs:
  build:
    name: Deploy
    runs-on: host
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          echo "Workspace: ${{ gitea.workspace }}"
          echo "PWD: $(pwd)"
          ls -la
      - name: Deploy
        run: |
          docker container prune -f
          docker network prune -f
          docker image prune -f --filter "until=24h"
          docker builder prune -f --filter "until=168h"

          docker compose -p "viperlith" down --remove-orphans
          docker compose -p "viperlith" --env-file .env.example up --build -d
        env:
          SESSION_KEY: ${{ secrets.SESSION_KEY }}